### PR TITLE
feat(styles): update typography and colors

### PR DESCRIPTION
**Pull request by 100stacks**
## Description

Update styles - typography and colors.

### What are the relevant story cards/tickets? Any additional PRs or other references?

Jira: SURF-2138

## Before you request a review for this PR:

- [x] For UI changes, did you manually test in recent versions of modern browsers (Chrome, Firefox, and Safari)?
- [x] For UI changes, did you manually test in IE11 and legacy Edge?
- [ ] Did you add component tests for any new code?
- [ ] Did you run the component unit tests via `yarn test` to ensure all tests passed?
- [ ] Did you include a screenshot of the component tests?
- [ ] If you changed/added functionality, did you update the demo page and documentation?
- [ ] If needed, did you add or modify the demo test page to test the changed/added functionality?
- [x] Did you assign reviewers?
- [x] In Jira, have you linked to this PR on the ticket(s)?

### CODE REVIEW

**Review by lalithkarikelli — APPROVED** [review]
DEV LGTM

**Review by BY00565233 — APPROVED** [review]
DEV LGTM

**Review by 100stacks — COMMENTED** [review]
### @danielmdesigns this PR includes typography and color updates.  Please see:

#### https://deploy-preview-797--helix-ui.netlify.app/components/typography

**Review by danielmdesigns — CHANGES_REQUESTED** [review]
it looks like base styles and colors need to be updated per our design specs. we have updated typography sepcs coming later today and we should align to those updates.

**Review by 100stacks — COMMENTED** [review]
> it looks like base styles and colors need to be updated per our design specs. we have updated typography sepcs coming later today and we should align to those updates.

Updated heading styles.

**Review by 100stacks — COMMENTED** [review]
#### @danielmdesigns, I'm going to merge this PR #797 and we'll iterate on updates.

**Pull request merged**
